[package]
name = "mochiOS"
version = "0.0.1-dev"
edition = "2021"
authors = ["tas0dev"]
default-run = "boot"

[workspace]
members = [".", "crates/mdriver-protocol"]

[[bin]]
name = "boot"
path = "src/loader.rs"
required-features = ["uefi-dep"]
test = false
bench = false

[[bin]]
name = "mochios-system"
path = "src/system_domain.rs"
required-features = ["system-domain"]
test = false
bench = false

[[bin]]
name = "mdriver-probe"
path = "src/domain_probe.rs"
required-features = ["mdriver-probe"]
test = false
bench = false

[[bin]]
name = "domain-bootstrap"
path = "src/domain_entry.rs"
required-features = ["domain-probes"]
test = false
bench = false

[[bin]]
name = "hardware-bootstrap"
path = "src/hardware_bootstrap.rs"
required-features = ["domain-probes"]
test = false
bench = false

[[bin]]
name = "event-bootstrap"
path = "src/event_bootstrap.rs"
required-features = ["domain-probes"]
test = false
bench = false

[[bin]]
name = "grant-bootstrap"
path = "src/grant_bootstrap.rs"
required-features = ["domain-probes"]
test = false
bench = false

[[bin]]
name = "ring-bootstrap"
path = "src/ring_bootstrap.rs"
required-features = ["domain-probes"]
test = false
bench = false

[features]
default = ["uefi-dep"]
uefi-dep = ["dep:uefi"]
system-domain = ["dep:mnu"]
mdriver-probe = []
domain-probes = []
kcfi = []
cet-ibt = []
cet-shadow-stack = []

[dependencies]
uefi = { version = "0.30", features = ["alloc", "logger", "global_allocator"], optional = true }
spin = "0.9.9"
x86_64 = "0.15"
linked_list_allocator = "0.10.5"
sha2 = { version = "0.10", default-features = false, features = ["force-soft"] }
mnu-abi = { git = "https://github.com/mochiOS/mnu", package = "mnu-abi" }
mnu = { git = "https://github.com/mochiOS/mnu", default-features = false, optional = true }
mochios-mdriver-protocol = { path = "crates/mdriver-protocol" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
