[package]
name = "mochios-system-image"
version = "0.1.0"
edition = "2021"

[features]
default = []
std = ["ed25519-dalek/std", "sha2/std", "dep:base64"]

[dependencies]
base64 = { version = "0.22", optional = true }
ed25519-dalek = { version = "2", default-features = false }
sha2 = { version = "0.10", default-features = false, features = ["force-soft"] }

[[bin]]
name = "system-image-sign"
path = "src/bin/sign.rs"
required-features = ["std"]

[[bin]]
name = "system-slot-image"
path = "src/bin/slot.rs"
required-features = ["std"]
