# mochiOS policy passed to the mnu System Domain kernel.
capability.path.binary=/bin
capability.path.binary=/applications
capability.path.system=/system
capability.path.libraries=/libraries
capability.path.tmp=/tmp
capability.path.config=/config
capability.path.var=/var
capability.path.mount=/mount
capability.path.user=/home

policy.identity_storage_root=/libraries/applications
policy.shared_configuration_root=/var/config
policy.execution_allowlist=/libraries/system/execution.allowlist
policy.audit_log=/system/logs/audit.log
policy.process_aliases=/config/drivers.list
